services:
  grafana:
    build:
      context: ./
      dockerfile: Dockerfile
    image: mioboxgraf:latest
    entrypoint: /run.sh
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
    volumes:
      - ./dist:/var/lib/grafana/plugins/business-app
      - ./provisioning:/etc/grafana/provisioning
