version: '3.8'  # Specify the Compose file version  

services:  
  grafana:  
    image: miometrix/miobox-dash
    ports:  
      - "3000:3000"  
    environment:  
      - GF_DEFAULT_APP_MODE=production  
    volumes:  
      - dist:/var/lib/grafana/plugins/business-app  
      - provisioning:/etc/grafana/provisioning  

volumes:  
  dist:        # Define the 'dist' volume  
  provisioning: # Define the 'provisioning' volume  